name: frontiers-emulator-env
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - jupyter_nbextensions_configurator=0.4.1
  - matplotlib=3.6.1
  - matplotlib-inline>=0.1.6
  - nbconvert=5.6.1
  - nbclient==0.6.6
  - numpy=1.23.1
  - pandas=1.4.3
  - pip=22.2.2
  - python=3.9.13
  - pytest=7.1.3
  - scikit-learn=1.1.2
  - scipy=1.9.0
  - seaborn=0.11.2
