project:
  type: book

book:
  title: "BUQEYE Guide to Emulators in Nuclear Physics"
  author: "Christian Drischler, Dick Furnstahl, Alberto Garcia, Jordan Melendez, Xilin Zhang"
  date: "8/14/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - test.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



