project:
  type: book
  title: "BUQEYE Guide to Projection-Based Emulators in Nuclear Physics"
  # render:
  #   # - mymacros.tex
  #   # - macros.qmd
  #   - index.qmd
  #   - intro.qmd
  #   - model-reduction.qmd
  #   - eigen-emulators.qmd
  preview:
    port: 1234
  output-dir: _output

book:
  title: "BUQEYE Guide to Projection-Based Emulators in Nuclear Physics"
  author:
    - name: Christian Drischler
      affiliation: Ohio University, Facility for Rare Isotope Beams
      orcid: 0000-0003-1534-6285
    - name: Dick Furnstahl
      affiliation: The Ohio State University
      orcid: 0000-0002-3483-333X
    - name: Alberto Garcia
      affiliation: The Ohio State University
      orcid: 0000-0003-1723-3225
    - name: Jordan Melendez
      affiliation: The Ohio State University
      orcid: 0000-0003-1359-1594
    - name: Xilin Zhang
      affiliation: Facility for Rare Isotope Beams
      orcid: 0000-0001-9278-5359
  date: "11/08/2022"
  cover-image: buqeye_logo_web.png
  favicon: buqeye_logo_web.png
  repo-url: "https://github.com/buqeye/frontiers-emulator-review"
  repo-actions: [source, issue]
  # description: "Supplemental material for our guide to emulators"
  abstract: |
    The BUQEYE collaboration (Bayesian Uncertainty Quantification: Errors in Your EFT) presents a pedagogical introduction
    to projection-based, reduced-order emulators for applications in low-energy nuclear physics.
    The term *emulator* refers here to a fast surrogate model
    capable of reliably approximating high-fidelity models.
    As the general tools employed by these emulators are not yet well known in the nuclear physics community, we discuss variational and Galerkin projection methods, emphasize the benefits of offline-online decompositions, and explore how these concepts lead to emulators for bound and scattering systems that enable fast \& accurate calculations using many different model parameter sets.
    We also point to future extensions and applications of these emulators for nuclear physics, guided by the mature field of model (order) reduction.
    All examples discussed here and more are available as interactive, open-source Python code so that practitioners
    can readily adapt projection-based emulators for their own work.

  chapters:
    - index.qmd
    - intro.qmd
    - eigen-emulators.qmd
    - model-reduction.qmd
    - scattering-emulators.qmd
    - summary.qmd
    - references.qmd
  sidebar:
    logo: buqeye_logo_web.png
  downloads: [pdf, epub]

website:
  title: "BUQEYE Guide to Projection-based Emulators in Nuclear Physics"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - intro.qmd
      - model-reduction.qmd
      - eigen-emulators.qmd

bibliography:
  - bayesian_refs.bib

csl: phys_rev_c.csl

format:
  html:
    theme: cosmo
    top-level-division: section
    reference-location: margin
    citation-location: margin
    fig-width: 3.4
    fig-height: 3
    fig-dpi: 900
    fig-format: png
    crossref:
      eq-prefix: "" #"Eq."
      fig-prefix: "" #"Figure"
      sec-prefix: "" #"Section"
    language:
      crossref-ch-prefix: "" #"Section"
  pdf:
    # documentclass: scrreprt
    documentclass: template-2022/frontiersinFPHYFAMS
    classoption: utf8
    top-level-division: section
    toc: false
    keep-tex: true
    pdf-engine: pdflatex
    latex-auto-install: false # Faster if false. Change to true for publishing
    fig-pos: "tb"
    fig-width: 3.4
    fig-height: 3
    fig-dpi: 1000
    fig-format: png
    include-in-header:
      - preamble.tex
      - mymacros.tex
      - text: |
          \usepackage{xtab}
          \usepackage{isotope}
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          % Redefine longtable because it doesn't work in multicolumn
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          \makeatletter
          \def\longtable{\@ifnextchar[\newlongtable@i \newlongtable@ii}
          \def\newlongtable@i[#1]{%
          \renewcommand{\endhead}{\ignorespaces}
          \xtabular[#1]}
          \def\newlongtable@ii{%
          \renewcommand{\endhead}{\ignorespaces}
          \xtabular}
          \def\endlongtable{\endxtabular}
          \makeatother
    crossref:
      eq-prefix: "" #"Eq."
      fig-prefix: "" #"Figure"
      sec-prefix: "" #"Section"
    language:
      crossref-ch-prefix: "" #"Section"
    template-partials:
      - partials/title.tex
