
::: {.content-hidden when-format="pdf"}
# Preface {.unnumbered}

If you find our "BUQEYE Guide for Projection-based Emulators in nuclear physics" helpful, please cite our work:
```bibtex
@article{Drischler:2022ipa,
    author = "Drischler, C. and Melendez, J. A. and Furnstahl, R. J. and Garcia, A. J. and Zhang, Xilin",
    title = "{BUQEYE Guide to Projection-Based Emulators in Nuclear Physics}",
    eprint = "2212.04912",
    archivePrefix = "arXiv",
    primaryClass = "nucl-th",
    month = "12",
    JOURNAL={Front. Phys.},      
    VOLUME={10},
    pages=92931,
    YEAR={2023},      
    URL={https://www.frontiersin.org/articles/10.3389/fphy.2022.1092931},       
    DOI={10.3389/fphy.2022.1092931},      
    ISSN={2296-424X}   
}
```
:::

# Funding {.unnumbered}
This material is based upon work supported by the U.S. Department of Energy, Office of Science, Office of Nuclear Physics, under the FRIB Theory Alliance award DE-SC0013617.
This work was supported in part by the National Science Foundation under award numbers PHY-1913069 and PHY-2209442 and the NSF CSSI program under award
number OAC-2004601 (BAND Collaboration @BAND_Framework), and the NUCLEI SciDAC Collaboration under U.S. Department of Energy MSU subcontract RC107839-OSU.


# Acknowledgments {.unnumbered}
We thank the Editors Maria Piarulli, Evgeny Epelbaum, and Christian Forssén for the kind invitation to contribute to this Frontiers Research Topic @ResearchTopicUQ.
We are also grateful to our BUQEYE @BUQEYEweb and BAND @BAND_Framework collaboration colleagues for sharing their invaluable insights with us, and especially to Pablo Giuliani and Daniel Phillips for fruitful discussions.
C.D. thanks Petar Mlinarić for sharing his deep insights into the software library **pyMOR** @milk2016pyMOR for building MOR applications with the Python.
