::: {.hidden}
{{< include macros.qmd >}}
:::

# Introduction

Nuclear systems are notoriously complex. But typically, our theoretical modeling of nuclear phenomena contains superfluous information for quantities of interest.
Model order reduction (MOR) refers to powerful techniques that enable us to reduce a system's complexity systematically (_e.g._, see References [@Benner_2017aa; @Benner2017modelRedApprox; @benner2015survey] for comprehensive introductions).
These techniques enable emulators,
which are low-dimensional surrogate models capable of rapidly and reliably approximating high-fidelity models,
making practical otherwise impractical calculations.
But the nuclear physics community has barely scratched the surface of the types of emulators that could be crafted or explored their full range of applications.

A fertile area for new emulators is uncertainty quantification (UQ) [@Zhang:2015ajn; @Neufcourt:2019qvd; @King:2019sax; @Ekstrom:2019lss; @Catacora-Rios:2020xgx; @Wesolowski:2021cni; @Svensson:2021lzs; @Odell:2021tqd; @Djarv:2021pjc; @Alnamlah:2022eae] in nuclear physics, which is the general theme of this Frontiers Research Topic @ResearchTopicUQ.
Quantifying theoretical uncertainties rigorously is crucial for comparing theory predictions with experimental and/or observational constraints and performing model comparison and/or mixing~\cite{Phillips:2020dmw}.
However, UQ has only recently drawn much attention as nuclear theory has entered the precision era.
Bayesian parameter estimation for nuclear effective field theory (EFT) and optical models, UQ for nuclear structure pushing toward larger masses and for reactions across the chart of nuclides, experimental design [@Melendez:2020ikd; @Phillips:2020dmw; @Farr:2021fyc] for the next generation of precision experiments probing the nuclear dripline,
and many other applications
will all benefit from emulators.
This Research Topic~\cite{ResearchTopicUQ} already contains several new applications of emulators for nuclear physics.
Key to the wider adoption of these tools is the evangelization of their potential and the creation of pedagogical guides for those first starting in this field @Melendez:2022kid.
This article is aimed at  both goals.

To do so, the BUQEYE collaboration (Bayesian Uncertainty Quantification: Errors in Your EFT) @BUQEYEweb has created a rather unconventional document comprised of the article you are reading now along with a companion website @companionwebsite containing interactive supplemental material and source code that generates all the results shown, and much more.
Interested individuals can dynamically generate different versions of this document based on tunable parameters.
We hope that this format encourages readers to experiment and build upon the examples presented here, thereby facilitating new applications.

Various types of emulators have already been applied with success within nuclear physics.
A non-exhaustive list of applications includes References [@Higdon:2014tva; @Frame:2017fah; @Sarkar:2020mad; @Sarkar:2021fpz; @Konig:2019adq; @Demol:2019yjt; @Ekstrom:2019lss; @Bai:2021xok; @Demol:2020mzd; @Yoshida:2021jbl; @Wesolowski:2021cni; @Furnstahl:2020abp; @Melendez:2021lyq; @Drischler:2021qoy; @Zhang:2021jmi; @Drischler:2022yfb; @Anderson:2022jhq; @Giuliani:2022yna; @Surer:2022lhs; @Bai:2022hjg; @Kravvaris:2020lhp; @Yapa:2022nnv; @Francis:2022zib; @Zare:2022cdw].
But as emphasized in References [@Melendez:2022kid; @Bonilla:2022rph], there is a broad and relatively mature MOR literature outside of nuclear physics waiting to be exploited (_e.g._, see Reference @Benner2020Volume1DataDriven for an overview of the universe of MOR approaches).
Our goal in this guide will be to facilitate this exploitation through a selective treatment of physics-informed, projection-based emulators relevant to a wide range of nuclear physics problems.

To this end, we organize this guide as follows. Section @sec-eigen-emulators focuses on emulators for bound-state calculations using subspace-projection methods.
We then provide a more general introduction to MOR for solving differential equations in Section @sec-model-reduction, which leads to our discussion of scattering emulators in Section @sec-scattering-emulators.
Section @sec-conclusion concludes with a summary and outlook.
Throughout, we draw connections between variational and Galerkin projection methods and illustrate these concepts with pedagogical examples, supplemented by source code on the companion website @companionwebsite.
